/**
 * Generated by `npm run gen:api` from the backend's OpenAPI document.
 * Do not edit by hand: regenerate after changing a route or a response model.
 */
export interface paths {
    "/api/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Back up the database */
        post: operations["post_backup_api_backup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/device/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-sent stream of the merged live status
         * @description Every merged `evt:status`, plus connection changes.
         *
         *     The status is already merged server-side (one socket, one merge) so each
         *     event is the whole picture and a tab that joins mid-shot is immediately
         *     correct. Heartbeat comments come from ``sse_response``; without them a
         *     reverse proxy closes an idle stream between shots.
         */
        get: operations["get_device_live_api_device_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/device/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Connection state, identity and the last known live status */
        get: operations["get_device_status_api_device_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read all runtime settings */
        get: operations["get_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update runtime settings */
        patch: operations["patch_settings_api_settings_patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and readiness */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApiError
         * @description The error half of the envelope.
         */
        ApiError: {
            /** Code */
            code: string;
            /** Details */
            details?: unknown;
            /** Message */
            message: string;
        };
        /**
         * ApiMeta
         * @description Envelope metadata. Always carries the request id the server logged under.
         */
        ApiMeta: {
            /** Request Id */
            request_id: string;
        };
        /** ApiResponse[BackupData] */
        ApiResponse_BackupData_: {
            data?: components["schemas"]["BackupData"] | null;
            error?: components["schemas"]["ApiError"] | null;
            meta: components["schemas"]["ApiMeta"];
            /** Ok */
            ok: boolean;
        };
        /** ApiResponse[DeviceStatusData] */
        ApiResponse_DeviceStatusData_: {
            data?: components["schemas"]["DeviceStatusData"] | null;
            error?: components["schemas"]["ApiError"] | null;
            meta: components["schemas"]["ApiMeta"];
            /** Ok */
            ok: boolean;
        };
        /** ApiResponse[HealthData] */
        ApiResponse_HealthData_: {
            data?: components["schemas"]["HealthData"] | null;
            error?: components["schemas"]["ApiError"] | null;
            meta: components["schemas"]["ApiMeta"];
            /** Ok */
            ok: boolean;
        };
        /** ApiResponse[SettingsData] */
        ApiResponse_SettingsData_: {
            data?: components["schemas"]["SettingsData"] | null;
            error?: components["schemas"]["ApiError"] | null;
            meta: components["schemas"]["ApiMeta"];
            /** Ok */
            ok: boolean;
        };
        /**
         * BackupData
         * @description Where the backup was written.
         */
        BackupData: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Filename */
            filename: string;
            /** Path */
            path: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /**
         * DeviceStatusData
         * @description What `GET /api/device/status` answers.
         *
         *     ``configured`` and ``connected`` are separate facts and the UI needs both:
         *     "no machine configured" is a setup step, "configured but not connected" is a
         *     problem to go and look at.
         */
        DeviceStatusData: {
            /** Configured */
            configured: boolean;
            /** Connected */
            connected: boolean;
            /** Host */
            host?: string | null;
            /** Identity */
            identity?: {
                [key: string]: unknown;
            } | null;
            /** Last Status */
            last_status?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * HealthData
         * @description The health payload.
         */
        HealthData: {
            /** Database */
            database: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * SettingsData
         * @description Registry key -> resolved setting. Secrets carry a hint, never a value.
         */
        SettingsData: {
            [key: string]: unknown;
        };
        /**
         * SettingsPatchBody
         * @description ``{"gaggimateHost": "10.0.0.5", "llmModel": null}``
         */
        SettingsPatchBody: {
            [key: string]: components["schemas"]["SettingValue"];
        };
        SettingValue: string | number | boolean | null;
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_backup_api_backup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_BackupData_"];
                };
            };
        };
    };
    get_device_live_api_device_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_device_status_api_device_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_DeviceStatusData_"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_SettingsData_"];
                };
            };
        };
    };
    patch_settings_api_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatchBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_SettingsData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_HealthData_"];
                };
            };
        };
    };
}
