#!/usr/bin/env node
/**
 * Regenerate `src/api/schema.d.ts` from the backend's OpenAPI document.
 *
 * Two sources, in order:
 *
 *  1. The Python app itself, via `uv run python -c "... create_app().openapi()"`.
 *     This is the default because it needs no server, no port and no network —
 *     it works offline, in CI and inside a fresh checkout.
 *  2. A running backend, when `GAGGICLANKER_OPENAPI_URL` is set (or `--url` is
 *     passed). Useful against a container you cannot import from.
 *
 * The generated file is committed: a type-check must not depend on having a
 * Python toolchain, and a diff in it is exactly the signal you want when the
 * backend contract moves.
 */

import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const here = path.dirname(fileURLToPath(import.meta.url));
const webRoot = path.resolve(here, "..");
const repoRoot = path.resolve(webRoot, "..");
const outFile = path.join(webRoot, "src", "api", "schema.d.ts");

const urlArgIndex = process.argv.indexOf("--url");
const url =
  (urlArgIndex !== -1 ? process.argv[urlArgIndex + 1] : undefined) ??
  process.env.GAGGICLANKER_OPENAPI_URL;

const EXPORT_SNIPPET =
  "import json; from gaggiclanker.main import create_app; " +
  "print(json.dumps(create_app().openapi()))";

function schemaFromPython() {
  const result = spawnSync("uv", ["run", "--frozen", "python", "-c", EXPORT_SNIPPET], {
    cwd: repoRoot,
    encoding: "utf8",
    maxBuffer: 32 * 1024 * 1024,
  });
  if (result.error) {
    throw new Error(
      `could not run uv (${result.error.message}). Install it with \`pip install --user uv\`, ` +
        "or point this script at a running backend with --url / GAGGICLANKER_OPENAPI_URL.",
    );
  }
  if (result.status !== 0) {
    throw new Error(`uv run failed (exit ${result.status}):\n${result.stderr}`);
  }
  // create_app() configures structlog, which may write to stdout before the
  // JSON. Take the last line, which is the print() above.
  const lines = result.stdout.trim().split("\n");
  return JSON.parse(lines[lines.length - 1]);
}

async function schemaFromUrl(target) {
  const response = await fetch(target);
  if (!response.ok) {
    throw new Error(`GET ${target} -> ${response.status}`);
  }
  return await response.json();
}

const schema = url ? await schemaFromUrl(url) : schemaFromPython();

const ast = await openapiTS(schema, { alphabetize: true });
const banner = [
  "/**",
  " * Generated by `npm run gen:api` from the backend's OpenAPI document.",
  " * Do not edit by hand: regenerate after changing a route or a response model.",
  " */",
  "",
].join("\n");

mkdirSync(path.dirname(outFile), { recursive: true });
writeFileSync(outFile, banner + astToString(ast), "utf8");
console.log(`wrote ${path.relative(webRoot, outFile)} (${url ? url : "uv run python"})`);
