import type { ShotDetailData, ShotSampleRow, ShotSamplesData } from "@/api/types";
import rawFixture from "@/test/fixtures/shot-129.json?raw";

/**
 * The maintainer's own shot 129, in the shape `/api/shots/{id}` answers.
 *
 * Generated by importing `tests/fixtures/exports/shot-129.json` through the
 * real importer and dumping the rows — so the phases, the diagnostics, the
 * band labels and the execution score in it were computed by
 * `gaggiclanker/domain/diagnostics.py`, not written by hand. A front-end test
 * against a hand-written diagnostics blob proves only that the test author and
 * the component agree.
 *
 * Imported `?raw` and parsed rather than imported as JSON: it is 213 samples,
 * and asking TypeScript to infer a literal type for every field of every one
 * of them costs more than the whole rest of the type-check.
 *
 * Regenerate it after a diagnostics change — the command is in `web/README.md`.
 */
const raw = JSON.parse(rawFixture) as { detail: ShotDetailData; samples: ShotSamplesData };

export const shot129: ShotDetailData = raw.detail;
export const shot129Samples: ShotSamplesData = raw.samples;

/** 213 samples at 250 ms — a 54.6 s shot with four phases. */
export const SHOT_129_SAMPLE_COUNT = 213;

/**
 * A synthetic curve of `count` samples at 250 ms, for the cases the real shot
 * cannot cover: a 60-second shot for the render budget, and a machine with no
 * pressure sensor.
 */
export function syntheticSamples(
  count: number,
  options: { hasPressure?: boolean; hasScale?: boolean } = {},
): ShotSampleRow[] {
  const { hasPressure = true, hasScale = true } = options;
  return Array.from({ length: count }, (_, index) => {
    const t = index * 250;
    const progress = index / Math.max(1, count - 1);
    return {
      t_ms: t,
      tt: 93,
      ct: 92.4 + Math.sin(index / 7) * 0.3,
      tp: hasPressure ? 9 : null,
      cp: hasPressure ? Math.min(9, 0.5 + index * 0.25) : null,
      fl: hasPressure ? 2.2 - progress * 0.6 : null,
      tf: hasPressure ? 2 : null,
      pf: hasPressure ? 1.9 - progress * 0.5 : null,
      vf: hasScale ? 1.8 : null,
      v: hasScale ? progress * 36 : null,
      ev: progress * 35,
      pr: hasPressure ? 4.5 : null,
      si: 0x000b,
      wp: progress * 40,
      phase_number: index < count / 4 ? 0 : 1,
    };
  });
}
